application: grounded-vista-351
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: latest

handlers:
- url: /facebook/\d+
  script: facebook.application
